language: python
install:
  - pip install quandl
  - pip install Jinja2
  - pip install PyYAML
  - apt-get install mysql-server
script:
  - pwd
  - export PYTHONPATH=${PYTHONPATH}:./scripts/dcf
  - python ./scripts/test_dcf.py
